name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (Server, Client, Web)
        run: |
          npm ci
          cd web
          npm ci

      - name: Build scripts (Server, Client)
        run: |
          npm run build

      - name: Build web
        run: |
          cd web
          npm run build

      - name: Reorganize output structure
        run: |
          mkdir -p deploy/server deploy/client deploy/web
          cp -r build/server/* deploy/server/
          cp -r build/client/* deploy/client/
          cp -r web/build/* deploy/web/

      - name: Show deploy directory structure
        run: |
          echo "Deploy directory structure:"
          ls -R deploy

      - name: Deploy to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: deploy
          target: /home/gta/
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          overwrite: true
          debug: true
