name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (Server, Client, Web)
        run: |
          npm ci
          cd web
          npm ci

      - name: Build server
        run: |
          npx webpack --config webpack.config.js --env target=server

      - name: Build client
        run: |
          npx webpack --config webpack.config.js --env target=client

      - name: Build web
        run: |
          cd web
          npm run build

      - name: Debug web build
        run: |
          echo "Checking contents of web/"
          ls -lah web
          echo "Checking contents of web/build/"
          ls -lah web/build || echo "dist does not exist"


      - name: Debug - show files
        run: |
          echo "== SERVER =="
          ls -lah server || echo "server folder missing"
          echo "== CLIENT =="
          ls -lah client || echo "client folder missing"
          echo "== WEB DIST =="
          ls -lah web/build || echo "web/build folder missing"

      - name: Deploy to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: |
            server/*
            client/*
            web/build/*
          target: /home/gta/
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          overwrite: true
          debug: true
