name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (Server, Client, Web)
        run: |
          npm ci
          cd web
          npm ci

      - name: Build scripts (Server, Client)
        run: |
          npm run build

      - name: Build web
        run: |
          cd web
          npm run build 

      - name: Debug - Show directory content
        run: |
          echo "Checking contents of build/server"
          ls -lah build/server || echo "No files found in build/server"
          echo "Checking contents of build/client"
          ls -lah build/client || echo "No files found in build/client"
          echo "Checking contents of web/build"
          ls -lah web/build || echo "No files found in web/build"

      - name: Deploy to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: |
            build/server/*
            build/client/*
            web/build/*
          target: /home/gta/
          port: 22
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          overwrite: true
          debug: true
          tar: true
